feat(BASE): send it
Uniswap/universal-router pull request #308
Opened 2023-07-10 15:48 UTC by JFrankfurt

2023-07-10 15:52 UTC, hensha256 commented on script/deployParameters/DeployBASEGoerli.s.sol
> +            seaportV1_5: UNSUPPORTED_PROTOCOL,
isnt unsupported - should be `0x00000000000000ADc04C56Bf30aC9d3c0aAF14dC`

2023-07-10 15:54 UTC, hensha256 commented on script/deployParameters/DeployBASEGoerli.s.sol
> +contract DeployBASEGoerli is DeployUniversalRouter {
In their docs, blogs etc its just Base not BASE

2023-07-10 15:55 UTC, hensha256 requested changes
Needs to support seaport too 🙏

2023-07-25 23:37 UTC, JFrankfurt commented
this adds goerli base support and we should include it

2023-07-26 15:44 UTC, ewilz commented on script/deployParameters/DeployBASEGoerli.s.sol
`DeployBaseGoerli.s.sol` ?

2023-07-26 15:44 UTC, ewilz commented on deploy-addresses/BASE-goerli.json
`base-goerli.json` ?

2023-07-28 16:04 UTC, merged